M48
; DRILL file {KiCad (6.99.0-1487-g4c225cff5b)} date Mon Mar 28 23:32:51 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-28T23:32:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-1487-g4c225cff5b)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X8.82Y-14.56
T2
X5.0Y-5.0
X5.0Y-60.0
X84.5Y-5.5
X85.0Y-60.0
T0
M30
